#!/usr/bin/env python

Import('env')

env.add_source_files(env.modules_sources, "*.cpp")
env.add_source_files(env.modules_sources, "core_api/*.cpp")

env.Append(LINKFLAGS=["-rdynamic"])
env.use_ptrcall = True

Export('env')
